# GitHub Actions workflow for the Auto Test Suite

name: Run Auto Tests

# This workflow is triggered by a repository_dispatch event.
# It's designed to be triggered by the taskmanager-app workflow after a new image is built.
on:
  repository_dispatch:
    types: [app-updated]
  push:
    branches: [main]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The default ubuntu-latest runner does not have docker-compose.
      # This step downloads and installs a specific version of docker-compose.
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run tests
        # If triggered by dispatch, use the SHA from the payload.
        # Otherwise (if triggered by push), default to 'latest'.
        env:
          APP_IMAGE_TAG: ${{ github.event.client_payload.sha || 'latest' }}
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from tests
          
      - name: Upload Allure Report
        # This action is always run, even if the previous step (tests) fails,
        # so you can see the report for failed tests.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact to be uploaded.
          name: allure-report
          # The path to the directory to upload.
          # This path is on the GitHub runner's filesystem.
          path: build/allure-report